### ISSUE TITLE
Certificate on airwf.org has expired

### ISSUE THREAD

**Issue by daenney** [sheng/air#2]
The redirect from https://airwf.org to https://github.com/sheng/air currently flags an error in my browser as the certificate issued by Lets Encrypt is only valid until the 2nd of June 2017. It seems the (auto)renewal of it has failed.

**Comment by sheng** [comment]
The problem has been solved. Thanks for reminding me. 😊

**Comment by elisaado** [comment]
The domain expired now, rip.
